
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["busboy", "@netlify/blobs"]

[build]
  publish = "."
  command = "npm install"
  functions = "functions"

[dev]
  functions = "functions"
  publish = "."