
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["busboy", "@netlify/blobs"]

[build]
  publish = "."
  command = "npm install && sed -i 's|__AUTH0_DOMAIN__|'$SECRET_AUTH0_DOMAIN'|g' auth0.html && sed -i 's|__AUTH0_CLIENT_ID__|'$SECRET_AUTH0_CLIENT_ID'|g' auth0.html"
  functions = "functions"

[dev]
  functions = "functions"
  publish = "."